try:
    num=10
    print(num)
    raise ValueError
except:
    print("Exception occured ....program terminating...")